### PR TITLE
SYB-1632 SYB-1658 Add settings for download limits (for scheduled prefetch)

### PR DESCRIPTION
**Pull request by hrydgard**
Why are these settings in Utils and not in auth-lib along with the SoundZone object anyway? :)

### CODE REVIEW

**Comment by sfro** [comment]
Because ScheduleSettings is in another service and we wanted to collect all settings in one place.

**Comment by hrydgard** [comment]
@sfro  fair enough. Any objections otherwise? You can see the UI for these settings here: https://soundtrackyourbrand.atlassian.net/browse/SYB-1633

**Comment by sfro** [comment]
Looks good!

Since @fredr has started work on us being able to do cross-service calls without having to use utils, we will probably move sound zone settings directly in sound zones.

**Comment by avocade** [comment]
Just FYI, we're changing the name from "TuneinEnabled" to "Discoverable" in
utils, and in the rest of the backend. Was decided yesterday with carl and
patrik.

I've added a pull request to utils for the name change, but if you will
move all settings into soundzones, it's not needed... When will you do the
move?

On Wed, Apr 8, 2015 at 11:38 AM, sfro <notifications@github.com> wrote:

> Looks good!
>
> Since @fredr <https://github.com/fredr> has started work on us being able
> to do cross-service calls without having to use utils, we will probably
> move sound zone settings directly in sound zones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soundtrackyourbrand/utils/pull/26#issuecomment-90862782>
> .
>



-- 
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
*Oskar Boethius Lissheim*
Lead Developer iOS at *Soundtrack Your Brand* | *Exclusive Provider of
Spotify® for Business and **Spotify® for Enterprise*

Also Rails & Clojure Developer, Interaction Designer and certified
ScrumMaster.

   mobile:  +46-736-52-54-20
   work: soundtrackyourbrand.com
   me:   about.me/oskarlissheimboethius

I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by sfro** [comment]
Some time in the distant future probably. I was just commenting on the logic of having the settings directly in the sound zone in the future.

**Comment by avocade** [comment]
Aha... Then check my pull request for utils and please merge it into master if it looks ok ASAP :)

**Comment by hrydgard** [comment]
@sfro picked this up again after my detour to do metrics. Rebased it to match the new tunein change. This still looks fine? If so feel free to merge :)

**Comment by sfro** [comment]
Do you want to run Godep in syb-core first? Or just merge?

**Pull request closed without merging**
