### PR TITLE
SYB-1768 rename `tunein` to more generic `discoverable`

### PR DESCRIPTION
**Pull request by avocade**

### CODE REVIEW

**Comment by avocade** [comment]
Sync with https://github.com/soundtrackyourbrand/syb-core/pull/977

**Comment by sfro** [comment]
Maybe need a migration for this? If this is in production you may want to migrate the tunein field to the discoverable field.

**Comment by avocade** [comment]
Yup, but it's not in production, only on development. 

Can we do a manual migration with a script, or should we add a real migration even if it's not in production? 

How do we add a migration if so?

**Comment by sfro** [comment]
Ahaa, if it's just dev that's fine :D 
Also if it's just a few entities I guess you can go in manually.
We have a function called "RegisterMigration" that is defined in init() and runs in AfterLoad() (after it's loaded from datastore) for an entity.

**Comment by avocade** [comment]
Ok but the migration I'll add in SYB-core right?

So please merge this PR to master if looks ok :)

**Comment by fredr** [comment]
I readded the field, since master is production, and that field now already exists there. A migration is needed to remove it

**Comment by avocade** [comment]
I thought that the TuneinEnabled commit was never pushed to master before, only in the feature/tunein branch... Who merged it into master previously?

**Comment by frekw** [comment]
@avocade it seems you did; https://github.com/soundtrackyourbrand/utils/commit/b6b578b98fda31aec45a5f26d50a151e14f57c3b

**Comment by avocade** [comment]
Weird, can't remember that. We only needed it to be on the development server.

I've added a new migration that I'll push up here in a moment, moving TuneinEnabled -> Discoverable.

Then when that's deployed, we can add a new commit which removes the TuneinEnabled field (no migration is necessary for that according to Rickard).

**Pull request merged**
